FROM php:8.1-fpm-alpine
WORKDIR /www/app

RUN docker-php-ext-install pdo pdo_mysql
RUN apk add libxml2-dev && docker-php-ext-install soap
RUN apk add --update nodejs npm
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer
RUN docker-php-ext-install sockets

RUN apk add --update libzip-dev curl-dev &&\
    docker-php-ext-install curl




CMD sh -c " \
    composer install && \
    php artisan migrate && \
    php artisan storage:link && \
    php artisan key:generate && \
    php-fpm"
