FROM php:8.1-fpm-alpine3.16

RUN docker-php-ext-install sockets \
    && apk add libxml2-dev && docker-php-ext-install soap \
    && docker-php-ext-install pdo pdo_mysql \
    && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer \
    && apk add --update libzip-dev curl-dev \
    && docker-php-ext-install curl

RUN apk add --no-cache linux-headers \
	&& apk add --update --no-cache --virtual .build-dependencies $PHPIZE_DEPS\
    && apk add autoconf

RUN pecl install xdebug

  

WORKDIR /www/microservices/user

    
CMD sh -c " \
    composer install && \
    php artisan migrate &&\
    php artisan storage:link && \
    php artisan key:generate &&\
    php artisan passport:install --force &&\
    php artisan passport:keys --force &&\
    php-fpm"
